spring.application.name=presence-backend
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=false
spring.devtools.restart.poll-interval=1s
spring.devtools.restart.quiet-period=400ms
management.endpoints.web.exposure.include=health,info
